target 'FunFreedom_Example' do
  source ‘https://github.com/CocoaPods/Specs.git’
#  use_frameworks!
  inhibit_all_warnings!
  platform :ios, '9.0'
  pod 'FunFreedom', :path => '../'
  pod 'HandyJSON'
  target 'FunFreedom_Tests' do
    inherit! :search_paths

  end
end
